### ISSUE TITLE
No composer dependency on Laravel/Illuminate

### ISSUE THREAD

**Issue by alxy** [ivanomatteo/laravel-codice-fiscale#1]
Hi,
your package is a service provide for laravel and in fact[ extends a class](https://github.com/ivanomatteo/laravel-codice-fiscale/blob/master/src/LaravelCodiceFiscaleServiceProvider.php#L5) that is part of the Laravel framework. However, you are not listing any dependencies to laravel in your `composer.json`, which I think is a bad practice. Maybe you can fix that, so users also know with which Laravel versions it is compatible :)

**Comment by ades4827** [comment]
if it may be of interest I have prepared a new version which contains a change to the composer.json to make the package compatible
